apiVersion: v1
kind: Namespace
metadata:
  name:  api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-container
        image: ttl.sh/telepresence-demo-api-gateway:2h
        imagePullPolicy: Always
        ports:
        - name:  api
          port:  8080
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name:  api-gateway
  namespace: api
spec:
  selector:
    app:  api-gateway
  type:  ClusterIP
  ports:
  - name: api
    port:  80
    targetPort:  8080
    containerPort: 8080